# Banco H2
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:file:./data/simuladordb;DB_CLOSE_DELAY=-1
quarkus.datasource.username=sa
quarkus.datasource.password=

# ORM - cria as tabelas automaticamente pelas suas classes Java
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Swagger sempre disponível
quarkus.swagger-ui.always-include=true

# Configuração para o Jacoco funcionar com Quarkus
%test.quarkus.jacoco.data-file=target/jacoco.exec
%test.quarkus.jacoco.reuse-data-file=true